<?xml version="1.0" encoding="utf-8"?><Database Name="SampleDB" Class="SampleDBViewModelsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.view_product" Member="view_products">
    <Type Name="view_product">
      <Column Name="product_id" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="product_name" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="price" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>